export const CLINICIAN_NAME = 'Dr. Chikaodi Kay Mba'
export const CLINICIAN_CREDENTIALS = 'DNP, PMHNP-BC, CRNP, MS'
export const CLINICIAN_NAME_WITH_CREDENTIALS = `${CLINICIAN_NAME}, ${CLINICIAN_CREDENTIALS}`
